[package]
name = "num_to_words"
version = "0.1.0"
authors = ["andrewcushing <andyc.bt4567@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
